// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FinalBackendAPIProgramacion2.Models;

public partial class ArticuloRelacionado
{
    [Required]
    public int Id { get; set; }
    [Required]
    public int IdUsuario { get; set; }
    [Required]
    public int IdPrimerArticulo { get; set; }
    [Required]
    public int IdSegundoArticulo { get; set; }

    public virtual Articulo IdPrimerArticuloNavigation { get; set; }

    public virtual Articulo IdSegundoArticuloNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}