// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FinalBackendAPIProgramacion2.Models;

public partial class Final_Programacion_2Context : DbContext
{
    public Final_Programacion_2Context(DbContextOptions<Final_Programacion_2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Articulo> Articulo { get; set; }

    public virtual DbSet<ArticuloRelacionado> ArticuloRelacionado { get; set; }

    public virtual DbSet<Imagen> Imagen { get; set; }

    public virtual DbSet<RefreshToken> RefreshToken { get; set; }

    public virtual DbSet<Resena> Resena { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Articulo>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Descripcion).HasMaxLength(1000);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.Precio).HasColumnType("money");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(1000);

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Articulo)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Articulo_Usuario");
        });

        modelBuilder.Entity<ArticuloRelacionado>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.IdPrimerArticuloNavigation).WithMany(p => p.ArticuloRelacionadoIdPrimerArticuloNavigation)
                .HasForeignKey(d => d.IdPrimerArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ArticuloRelacionado_Articulo");

            entity.HasOne(d => d.IdSegundoArticuloNavigation).WithMany(p => p.ArticuloRelacionadoIdSegundoArticuloNavigation)
                .HasForeignKey(d => d.IdSegundoArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ArticuloRelacionado_Articulo1");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.ArticuloRelacionado)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ArticuloRelacionado_Usuario");
        });

        modelBuilder.Entity<Imagen>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Ruta)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.TipoDeRelacion)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Imagen)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Imagen_Usuario");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasColumnName("created_at");
            entity.Property(e => e.CreatedByIp)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("created_by_ip");
            entity.Property(e => e.ExpiresAt).HasColumnName("expires_at");
            entity.Property(e => e.LastUsedAt)
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnName("last_used_at");
            entity.Property(e => e.ReasonForRevoked)
                .HasMaxLength(200)
                .HasColumnName("reason_for_revoked");
            entity.Property(e => e.ReplacedByTokenId).HasColumnName("replaced_by_token_id");
            entity.Property(e => e.RevokedAt).HasColumnName("revoked_at");
            entity.Property(e => e.TokenHash)
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnName("token_hash");
            entity.Property(e => e.UserAgent)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("user_agent");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.RefreshToken)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RefreshToken_Usuario");
        });

        modelBuilder.Entity<Resena>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Descripcion).HasMaxLength(1000);

            entity.HasOne(d => d.IdArticuloNavigation).WithMany(p => p.Resena)
                .HasForeignKey(d => d.IdArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Resena_Articulo");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Resena)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Resena_Usuario");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Contrasena)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Rol).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}