// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;

namespace FinalBackendAPIProgramacion2.Models;

public partial class Final_Programacion_2Context : DbContext
{
    public Final_Programacion_2Context(DbContextOptions<Final_Programacion_2Context> options)
        : base(options)
    {
    }

    public DbSet<Imagen> Imagen { get; set; } = null!;

    public virtual DbSet<Articulo> Articulo { get; set; }

    public virtual DbSet<ArticuloRelacionado> ArticuloRelacionado { get; set; }

    public virtual DbSet<Resena> Resena { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Imagen>(entity =>
        {
            entity.ToTable("Imagen");

            entity.Property(e => e.Id).ValueGeneratedNever().IsRequired();
            entity.Property(e => e.Ruta).HasMaxLength(1000).IsRequired();
            entity.Property(e => e.TipoDeRelacion)
                  .IsRequired()
                  .HasMaxLength(20);
            entity.Property(e => e.IdRelacionado)
                  .IsRequired().ValueGeneratedNever();
        });

        modelBuilder.Entity<Articulo>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Descripcion).HasMaxLength(1000);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.Precio).HasColumnType("money");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(1000);

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Articulo)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Articulo_Usuario");
        });

        modelBuilder.Entity<ArticuloRelacionado>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.IdPrimerArticuloNavigation).WithMany(p => p.ArticuloRelacionadoIdPrimerArticuloNavigation)
                .HasForeignKey(d => d.IdPrimerArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ArticuloRelacionado_Articulo");

            entity.HasOne(d => d.IdSegundoArticuloNavigation).WithMany(p => p.ArticuloRelacionadoIdSegundoArticuloNavigation)
                .HasForeignKey(d => d.IdSegundoArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ArticuloRelacionado_Articulo1");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.ArticuloRelacionado)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ArticuloRelacionado_Usuario");
        });

        modelBuilder.Entity<Resena>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Descripcion).HasMaxLength(1000);

            entity.HasOne(d => d.IdArticuloNavigation).WithMany(p => p.Resena)
                .HasForeignKey(d => d.IdArticulo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Resena_Articulo");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Resena)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Resena_Usuario");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Contrasena)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Rol).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}