// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalBackendAPIProgramacion2.Models;

public partial class Imagen
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public string Ruta { get; set; }

    public int IdRelacionado { get; set; }

    public string TipoDeRelacion { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}