// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalBackendAPIProgramacion2.Models;

public partial class RefreshToken
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string TokenHash { get; set; }

    public DateTime ExpiresAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public string LastUsedAt { get; set; }

    public DateTime RevokedAt { get; set; }

    public string CreatedByIp { get; set; }

    public string UserAgent { get; set; }

    public int? ReplacedByTokenId { get; set; }

    public string ReasonForRevoked { get; set; }

    public virtual Usuario User { get; set; }
}