// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FinalBackendAPIProgramacion2.Models;

public partial class Resena
{
    [Required]
    public int Id { get; set; }
    [Required]
    public int IdUsuario { get; set; }
    [Required]
    public int IdArticulo { get; set; }
    [Required]
    public int Calificacion { get; set; }

    public string Descripcion { get; set; }

    public virtual Articulo IdArticuloNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}